services:
  planetary:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    command:
      sh -c "python manage.py wait_for_db &&
      python manage.py migrate &&
      python manage.py loaddata dump.json &&
      python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres:16.0-alpine3.17
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
